= Design Journal for SymbioSing UI

== By date

=== 2021-10-27

Kelsey and I discussed how we should represent data. Kelsey thinks of the actuation in terms of goal stretch sensor
values. It means that we will have to send to the FlowIO a list of pressure goals, and use PID controller scheme to
determine how to activate the valves. PID was suggested by Dag Svaenes.

=== 2021-10-28

After discussing with Kelsey, I decided to change colour scheme to dark. We discussed how we should present the
different buttons and multiple select, and Kelsey brought up that it would be used in a dark room so colours need to
be chosen appropriately, as well as using shapes and color combinations.

=== 2021-12-16

How do we do actuations? We have several possibilities now:

 . Actuations as timed instructions: Each gesture is a series of instructions defined by timing and low level
operations (opening and closing ports). We skulpt each gesture and then choose when to send it to the devices based
on the ML system.

 . Gestures as sensor goals: The ML system will send the next sensor values, and each garmet will decide on actuation
that will try and match these values using PID algorithm. This means that every FlowIO device will need 5 sensors,
and we assume that sensor readings are similar across instances.

 . Gestures as pressure goals: Similar to above, but we map from sensors to pressure values, and use an
actuated-measure loop on the FlowIO to control it. It would either require sampling each sensor separately, or use
the Sensor++ board.

 . Sensor goals, but calculated at the server: In this version one device from each tuple has all the sensors
connected to it. It sends readings to the server, which in turn will generate the new actions.

[cols="1,1,1"]
|===
|Solution |Advantages |Disadvantages

| Instructions
| Basically already implemented;
| Does not depend on garment state; Gestures need to be designed individually;

| On Device Sensor Goals
| Gestures are implicit for recorded/generated data; Fast control loop; Implemented (limited testing);
| Requires a sensor expansion for each FlowIO; makes assumptions about noise levels; Interpretation of sensor data
needs to be discussed;

| Pressure goals
| Can be implemented without additional hardware; Pressure sensor noise is low IIRC;
| Without Sensor++ board sampling pressure values is slow; Need to create mapping between sensor values and
pressure goals;

| Server Side Sensor Goals
| Gestures are implicitly generated; Server-side development is simpler; Only 1 FlowIO per triplet needs to have
sensors;
| Communication latency between sending sensor readings sending new instructions (might be lower than valve
activation latency anyway); Interpretation of sensor values needs to be discussed; Noise level might cause issues;
|===